
server:
  port: 8083

spring:
  application:
    name: dt-rmec-message-recovery
  dubbo:
    application:
      name: ${spring.application.name}
    registry:
       protocol: zookeeper
       address: localhost:2181
    protocol:
      name: dubbo
      port: ${server.port}
    scan: org.idreamlands.dt.message.api
  

  dtremc:
    message:
      handleduration: 180
      maxsendtimes: 5
      timeinterval:
        1: 0
        2: 1
        3: 2
        4: 5
        5: 15
