server:
  port: 8081

spring:
  application:
    name: dt-rmec-message

  rabbitmq:
    addresses: amqp://localhost:5672
    username: guest
    password: guest

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  jpa:
    generate-ddl: false
    show-sql: true
    properties: 
      hibernate: 
        format_sql: true
  dubbo:
    application:
      name: ${spring.application.name}
    protocol:
      name: dubbo
    registry:
      protocol: zookeeper
      address: localhost:2181
    scan: org.idreamlands.dt.message.api

message:
  maxsendtimes: 5