server:
  port: 8082

spring:
  application:
    name: dt-rmec-message-confirm
  dubbo:
    application:
      name: ${spring.application.name}
    registry:
       protocol: zookeeper
       address: localhost:2181
    protocol:
      name: dubbo
      port: ${server.port}
    scan: org.idreamlands.dt.message

  dtremc:
    message:
      handleduration: 180
      enablehttp: true